---
logging:
  level: info
  file: /var/vcap/sys/log/stager.log
pid_filename: /var/vcap/sys/run/stager.pid
nats_uri: nats://localhost:4222
max_staging_duration: 120
max_active_tasks: 10
queues: ['staging']
secure: false
