external_uri: api.gofoundry.net
description: "VMware's Cloud Application Platform"
support_address: http://help.ironfoundry.org
local_route: 10.91.2.12

allow_registration: false
allow_external_app_uris: true

# This dicatates what the uri namespace rules
# are for apps. Admins can overide any of the
# below accept taking a used uri.
app_uris:
  # Allow applications to register URIs that are outside your domain.
  allow_external: false
  reserved_list: [www, test, dash, register, foo, bar, api]
  reserved_length: 3
# reserved_file:

external_port: 9022 #public CC port

# nginx proxy provide multiple functions including offloading of file uploads/downloads.
nginx:
  use_nginx: false   # nginx proxy in front of CC?
  # instance_socket: /tmp/cloud_controller.sock
  insecure_instance_port: 9025 # debug only!!!! -- not for production use.

# if log_file is set, it must be a fully-qualified path,
# because the bin/vcap script reads it directly from the file.
logging:
  level: debug
  file: /var/vcap/sys/log/cc.log

# Settings for the rails logger
rails_logging:
  level: debug
  file: /var/vcap/sys/log/rails.log

redis:
  host: 127.0.0.1
  port: 5454
# password:

directories:
  droplets: /var/vcap/shared/droplets
  resources: /var/vcap/shared/resources

  # set to true to prevent filesystem resource leaks
  # nukes tmpdir on startup -- be careful!
  nuke_tmp_on_startup: false

  tmpdir: /var/vcap/data/cloud_controller/tmp

# NATS message bus URI
mbus: nats://localhost:4222/

keys:
  password: 'password key goes here'
  token: 'token key goes here'
  token_expiration: 604800 # 7 * 24 * 60 * 60 (= 1 week)

pid: /var/vcap/sys/run/cloudcontroller.pid
rails_environment: development
database_environment: # replaces database.yml
  production:
    database: cloudcontroller
    host: localhost
    port: 5432
    encoding: utf8
    username: postgres
    password: postgres
    adapter: postgresql
    timeout: 2000
    template: template0 # Required for utf8 encoding
  development:
    adapter: sqlite3
    database: db/cloudcontroller.sqlite3
    encoding: utf8
  test:
    adapter: sqlite3
    database: db/test.sqlite3
    encoding: utf8

# App staging parameters
staging:
  max_concurrent_stagers: 10
  # Max duration for staging process
  max_staging_runtime:    120 # secs
  # Create a secure environment for staging
  secure: false
  new_stager_percent: 0
  auth:
    user: zxsfhgjg
    password: ZNVfdase9

# admin support
admins: [luke.bakken@tier3.com, caledh@gmail.com, cale.hoopes@tier3.com, admin@ironfoundry.org]
https_required: false
https_required_for_admins: false

# Controls the amount of resources assigned to a user
# Normal user accounts
default_account_capacity:
  memory:   2048
  app_uris: 4
  services: 4
  apps:     4

# Services we provide, and their tokens. Avoids bootstrapping DB.
builtin_services:
  mssql:
    token: "0xdeadbeef"
  mysql:
    token: "0xdeadbeef"
  postgresql:
    token: "0xdeadbeef"
  redis:
    token: "0xdeadbeef"
  mongodb:
    token: "0xdeadbeef"
  rabbitmq:
    token: "0xdeadbeef"
  neo4j:
    token: "0xdeadbeef"
  atmos:
    token: "0xdeadbeef"

# Service broker
service_broker:
    token: "0xdeadbeef"

# Enable/disable starting apps in debug modes.
allow_debug: false

# Supported runtime versions and debug modes.
# Used for /info/runtimes endpoint (served unfiltered as JSON)
runtimes:
  aspdotnet40:
    version: 4.0.30319.0
  ruby18:
    version: 1.8.7
  ruby19:
    version: 1.9.2
  node:
    version: 0.4.12
  java:
    version: 1.6.0
    debug_modes:
      - run
      - suspend
  php:
    version: 5.3.[2-6]
  erlangR14B02:
    version: ".* 5.8.3"
  python26:
    version: 2.6.5

# Used for /healthz and /vars endpoints. If not provided random
# values will be generated on component start. Uncomment to use
# static values.
#status:
#  port: 34500
#  user: thin
#  password: thin
